name: Syntax highlighting Pipeline

on:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Repository auschecken
              uses: actions/checkout@v4

            - name: Java einrichten
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21

            - name: Build ausführen
              run: ./gradlew classes

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Repository auschecken
              uses: actions/checkout@v4

            - name: Java einrichten
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21

            - name: Tests ausführen
              run: ./gradlew test

    format:
        runs-on: ubuntu-latest

        steps:
            - name: Repository auschecken
              uses: actions/checkout@v4

            - name: Java einrichten
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21

            - name: Spotless prüfen
              run: ./gradlew spotlessCheck
